"""Generate a throwaway Ruby repository for giddyup to practise on.

The baseline commit is the point: everything the coding agent writes then shows
up as a working-tree change against it, so the analysis gate judges the agent's
diff rather than the whole directory.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

# Named so they cannot collide with what the stub coders write (invoice.rb,
# invoice_processor.rb) — the agent's changeset then contains only its own work.
BASELINE: dict[str, str] = {
    "README.md": "# Sandbox\n\nA practice repository generated by `mise run sandbox`.\n",
    "lib/catalog.rb": '''# frozen_string_literal: true

# A read-only list of products, keyed by SKU.
class Catalog
  def initialize(items)
    @items = items
  end

  def find(sku)
    @items[sku]
  end

  def size
    @items.size
  end
end
''',
    "lib/money.rb": '''# frozen_string_literal: true

# An amount in whole cents, kept integral to avoid floating point drift.
class Money
  attr_reader :cents

  def initialize(cents)
    @cents = cents
  end

  def add(other)
    Money.new(cents + other.cents)
  end

  def to_s
    format('$%.2f', cents / 100.0)
  end
end
''',
}

# An explicit identity keeps generation working on a machine with no global git
# config, without writing to the developer's configuration.
IDENTITY = ["-c", "user.name=giddyup sandbox", "-c", "user.email=sandbox@giddyup.invalid"]

# The subject of the baseline's root commit. Used both to create the baseline
# commit and, later, to recognise whether an existing directory IS one of our
# sandboxes (as opposed to some unrelated repository that happens to live at
# the requested path) before `force` is allowed to delete anything.
BASELINE_COMMIT_SUBJECT = "Baseline sandbox app"


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", *IDENTITY, *args], cwd=repo, check=True, capture_output=True)


def _git_output(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=repo, check=True, capture_output=True, text=True
    ).stdout.strip()


def _is_generated_sandbox(path: Path) -> bool:
    """Whether `path` is a git repo whose ROOT commit is our baseline commit.

    The root commit (not HEAD) is what we check, so a sandbox that has grown
    further commits on top of the baseline is still recognised as ours.

    A `.git` entry existing under `path` is not proof that `path` itself is a
    repository root: if it is not a valid repo (e.g. an empty directory), git
    discovery walks UP to an enclosing repository instead. We must confirm the
    discovered toplevel IS `path` before trusting anything git reports here —
    otherwise an enclosing generated sandbox's root commit can make an
    unrelated, non-empty subdirectory look like one of ours.
    """
    if not (path / ".git").exists():
        return False
    try:
        toplevel = _git_output(path, "rev-parse", "--show-toplevel")
        if Path(toplevel).resolve() != path.resolve():
            return False
        root_sha = _git_output(path, "rev-list", "--max-parents=0", "HEAD").splitlines()
        if not root_sha:
            return False
        subject = _git_output(path, "log", "-1", "--format=%s", root_sha[0])
    except subprocess.CalledProcessError:
        return False
    return subject == BASELINE_COMMIT_SUBJECT


def create_sandbox(path: Path, force: bool = False) -> Path:
    """Create a git repository with a clean Ruby baseline already committed.

    `path` may be missing or empty (proceeds normally), a sandbox this
    generator made earlier (replaced only when `force=True`), or something
    else non-empty (always refused — `force` never deletes a directory this
    generator didn't create).
    """
    path = Path(path)
    non_empty = path.exists() and any(path.iterdir())

    if non_empty:
        if _is_generated_sandbox(path):
            if not force:
                raise ValueError(
                    f"{path} is already a git repository; pass --force "
                    "(or force=True) to replace it"
                )
            shutil.rmtree(path)
        else:
            raise ValueError(
                f"{path} exists and is not a generated sandbox; remove it "
                "yourself if you really mean to replace it"
            )

    path.mkdir(parents=True, exist_ok=True)
    for name, source in BASELINE.items():
        target = path / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source, encoding="utf-8")

    _git(path, "init", "--initial-branch=main")
    _git(path, "add", "-A")
    _git(path, "commit", "-m", BASELINE_COMMIT_SUBJECT)
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="giddyup-sandbox",
        description="Generate a practice repository with a clean Ruby baseline.",
    )
    parser.add_argument("path", type=Path, nargs="?", default=Path("workspace"))
    parser.add_argument(
        "--force", action="store_true", help="Replace an existing sandbox."
    )
    args = parser.parse_args(argv)

    try:
        created = create_sandbox(args.path, force=args.force)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"git command failed: {exc}", file=sys.stderr)
        return 1

    print(f"Sandbox ready at {created}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
