"""Generate a throwaway Ruby repository for giddyup to practise on.

The baseline commit is the point: everything the coding agent writes then shows
up as a working-tree change against it, so the analysis gate judges the agent's
diff rather than the whole directory.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

# Named so they cannot collide with what the stub coders write (invoice.rb,
# invoice_processor.rb) — the agent's changeset then contains only its own work.
BASELINE: dict[str, str] = {
    "README.md": "# Sandbox\n\nA practice repository generated by `mise run sandbox`.\n",
    "lib/catalog.rb": '''# frozen_string_literal: true

# A read-only list of products, keyed by SKU.
class Catalog
  def initialize(items)
    @items = items
  end

  def find(sku)
    @items[sku]
  end

  def size
    @items.size
  end
end
''',
    "lib/money.rb": '''# frozen_string_literal: true

# An amount in whole cents, kept integral to avoid floating point drift.
class Money
  attr_reader :cents

  def initialize(cents)
    @cents = cents
  end

  def add(other)
    Money.new(cents + other.cents)
  end

  def to_s
    format('$%.2f', cents / 100.0)
  end
end
''',
}

# An explicit identity keeps generation working on a machine with no global git
# config, without writing to the developer's configuration.
IDENTITY = ["-c", "user.name=giddyup sandbox", "-c", "user.email=sandbox@giddyup.invalid"]


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", *IDENTITY, *args], cwd=repo, check=True, capture_output=True)


def create_sandbox(path: Path, force: bool = False) -> Path:
    """Create a git repository with a clean Ruby baseline already committed."""
    path = Path(path)
    if (path / ".git").exists():
        if not force:
            raise ValueError(
                f"{path} is already a git repository; pass force=True to replace it"
            )
        shutil.rmtree(path)

    path.mkdir(parents=True, exist_ok=True)
    for name, source in BASELINE.items():
        target = path / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source, encoding="utf-8")

    _git(path, "init", "--initial-branch=main")
    _git(path, "add", "-A")
    _git(path, "commit", "-m", "Baseline sandbox app")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="giddyup-sandbox",
        description="Generate a practice repository with a clean Ruby baseline.",
    )
    parser.add_argument("path", type=Path, nargs="?", default=Path("workspace"))
    parser.add_argument(
        "--force", action="store_true", help="Replace an existing sandbox."
    )
    args = parser.parse_args(argv)

    try:
        created = create_sandbox(args.path, force=args.force)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    print(f"Sandbox ready at {created}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
