# frozen_string_literal: true

source "https://rubygems.org"

ruby file: "../../.ruby-version"

# Static analysis, used as libraries rather than shelled-out CLIs.
gem "flay", "~> 2.13"
gem "flog", "~> 4.8"
gem "reek", "~> 6.5"

# HTTP boundary.
gem "puma", "~> 6.4"
gem "rack", "~> 3.1"

group :development, :test do
  gem "minitest", "~> 5.25"
  gem "rack-test", "~> 2.1"
  gem "rake", "~> 13.2"
end
